AWSTemplateFormatVersion: "2010-09-09"
Description: IAM roles for ECS Fargate tasks

Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: spacex-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: spacex-ecs-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

Outputs:
  ExecutionRoleArn:
    Description: ECS Execution Role ARN
    Value: !GetAtt ECSExecutionRole.Arn

  TaskRoleArn:
    Description: ECS Task Role ARN
    Value: !GetAtt ECSTaskRole.Arn
