AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SpaceX Launches Backend - Serverless Stack

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: spacex_launches

Resources:
  # DynamoDB Table
  SpaceXLaunchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: spacex_launches
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: launch_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: launch_date
          AttributeType: S
        - AttributeName: rocket_name
          AttributeType: S
        - AttributeName: launchpad
          AttributeType: S

      KeySchema:
        - AttributeName: launch_id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: GSI_Status
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: launch_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI_Rocket
          KeySchema:
            - AttributeName: rocket_name
              KeyType: HASH
            - AttributeName: launch_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI_Launchpad
          KeySchema:
            - AttributeName: launchpad
              KeyType: HASH
            - AttributeName: launch_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

        - IndexName: GSI_LaunchDate
          KeySchema:
            - AttributeName: launch_date
              KeyType: HASH
            - AttributeName: launch_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Ingest Lambda Function
  IngestLaunchesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: spacex-launches-ingest
      CodeUri: src/ingest
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SpaceXLaunchesTable
      Events:
        ManualInvoke:
          Type: Api
          Properties:
            Path: /api/v1/ingest
            Method: POST          

Outputs:
  DynamoDBTableName:
    Description: DynamoDB table name
    Value: !Ref SpaceXLaunchesTable

  IngestApiUrl:
    Description: API Gateway endpoint for ingest
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/ingest"
  
  
 


    
